-- Technical T05 probe only. This is not a business entity.

CREATE TABLE identity.identity_test_probe (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    probe_value varchar(100) NOT NULL
);

REVOKE ALL PRIVILEGES
    ON TABLE identity.identity_test_probe
    FROM PUBLIC, ${runtimeRole};

GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE identity.identity_test_probe
    TO ${runtimeRole};

REVOKE ALL PRIVILEGES
    ON SEQUENCE identity.identity_test_probe_id_seq
    FROM PUBLIC, ${runtimeRole};

GRANT USAGE, SELECT
    ON SEQUENCE identity.identity_test_probe_id_seq
    TO ${runtimeRole};

REVOKE ALL PRIVILEGES
    ON TABLE identity.flyway_schema_history
    FROM PUBLIC, ${runtimeRole};