management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      group:
        readiness:
          include: readinessState
  tracing:
    sampling:
      probability: 1.0

logging:
  structured:
    format:
      console: ecs
    ecs:
      service:
        name: __SERVICE_ID__
        environment: local
