-- TEST ONLY: all roles and credentials exist only in an ephemeral Testcontainer.
CREATE ROLE __ENV_PREFIX___test_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE __ENV_PREFIX___test_migrator LOGIN PASSWORD 'test-only-migrator-not-a-secret' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE __ENV_PREFIX___test_app LOGIN PASSWORD 'test-only-app-not-a-secret' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;

ALTER DATABASE __TEST_DB_NAME__ OWNER TO __ENV_PREFIX___test_owner;
REVOKE ALL PRIVILEGES ON DATABASE __TEST_DB_NAME__ FROM PUBLIC, __ENV_PREFIX___test_migrator, __ENV_PREFIX___test_app;
GRANT CONNECT ON DATABASE __TEST_DB_NAME__ TO __ENV_PREFIX___test_migrator, __ENV_PREFIX___test_app;

CREATE SCHEMA __SCHEMA_NAME__ AUTHORIZATION __ENV_PREFIX___test_migrator;
REVOKE ALL PRIVILEGES ON SCHEMA __SCHEMA_NAME__ FROM PUBLIC, __ENV_PREFIX___test_app;
GRANT USAGE, CREATE ON SCHEMA __SCHEMA_NAME__ TO __ENV_PREFIX___test_migrator;
GRANT USAGE ON SCHEMA __SCHEMA_NAME__ TO __ENV_PREFIX___test_app;
ALTER ROLE __ENV_PREFIX___test_migrator IN DATABASE __TEST_DB_NAME__ SET search_path TO __SCHEMA_NAME__, pg_catalog;
ALTER ROLE __ENV_PREFIX___test_app IN DATABASE __TEST_DB_NAME__ SET search_path TO __SCHEMA_NAME__, pg_catalog;

ALTER DEFAULT PRIVILEGES FOR ROLE __ENV_PREFIX___test_migrator IN SCHEMA __SCHEMA_NAME__
    REVOKE ALL PRIVILEGES ON TABLES FROM PUBLIC, __ENV_PREFIX___test_app;
ALTER DEFAULT PRIVILEGES FOR ROLE __ENV_PREFIX___test_migrator IN SCHEMA __SCHEMA_NAME__
    REVOKE ALL PRIVILEGES ON SEQUENCES FROM PUBLIC, __ENV_PREFIX___test_app;
REVOKE CONNECT ON DATABASE postgres FROM PUBLIC;
