CREATE TABLE __SCHEMA_NAME__.technical_probe (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    probe_value varchar(100) NOT NULL
);

REVOKE ALL PRIVILEGES ON TABLE __SCHEMA_NAME__.technical_probe FROM PUBLIC, ${runtimeRole};
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE __SCHEMA_NAME__.technical_probe TO ${runtimeRole};
REVOKE ALL PRIVILEGES ON SEQUENCE __SCHEMA_NAME__.technical_probe_id_seq FROM PUBLIC, ${runtimeRole};
GRANT USAGE, SELECT ON SEQUENCE __SCHEMA_NAME__.technical_probe_id_seq TO ${runtimeRole};
REVOKE ALL PRIVILEGES ON TABLE __SCHEMA_NAME__.flyway_schema_history FROM PUBLIC, ${runtimeRole};
